FAIL
run: should have called exit(-1): FAILED
